# Generated by Django 5.1.15 on 2026-06-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='icon',
            field=models.CharField(blank=True, max_length=40, verbose_name='Иконка (Ionicons)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='tagline',
            field=models.CharField(blank=True, max_length=160, verbose_name='Подзаголовок'),
        ),
    ]
