# Generated by Django 5.1.15 on 2026-06-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_seed_tariffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=80, verbose_name='Подпись')),
                ('accent', models.CharField(default='#1A1F71', max_length=9, verbose_name='Цвет акцента (hex)')),
                ('emblem', models.CharField(blank=True, max_length=10, verbose_name='Эмблема (текст)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включён')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['order', 'id'],
            },
        ),
    ]
