# Generated by Django 5.1.15 on 2026-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.CharField(blank=True, max_length=20, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='listing',
            name='body_type',
            field=models.CharField(blank=True, max_length=40, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='listing',
            name='call_from',
            field=models.CharField(blank=True, max_length=10, verbose_name='Звонить с'),
        ),
        migrations.AddField(
            model_name='listing',
            name='call_to',
            field=models.CharField(blank=True, max_length=10, verbose_name='Звонить до'),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, max_length=40, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='listing',
            name='customs',
            field=models.CharField(blank=True, max_length=20, verbose_name='Растаможен'),
        ),
        migrations.AddField(
            model_name='listing',
            name='deal_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Опции сделки'),
        ),
        migrations.AddField(
            model_name='listing',
            name='drive',
            field=models.CharField(blank=True, max_length=40, verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine',
            field=models.CharField(blank=True, max_length=40, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine_volume',
            field=models.CharField(blank=True, max_length=20, verbose_name='Объём двигателя'),
        ),
        migrations.AddField(
            model_name='listing',
            name='extra_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Доп. телефон'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gearbox',
            field=models.CharField(blank=True, max_length=40, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage_unit',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ед. пробега'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owners',
            field=models.CharField(blank=True, max_length=20, verbose_name='Владельцев'),
        ),
        migrations.AddField(
            model_name='listing',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.CharField(blank=True, max_length=80, verbose_name='Регион продажи'),
        ),
        migrations.AddField(
            model_name='listing',
            name='registration',
            field=models.CharField(blank=True, max_length=80, verbose_name='Учёт'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vin',
            field=models.CharField(blank=True, max_length=40, verbose_name='VIN'),
        ),
        migrations.AddField(
            model_name='listing',
            name='wheel',
            field=models.CharField(blank=True, max_length=20, verbose_name='Руль'),
        ),
    ]
