# Generated by Django 5.1.15 on 2026-06-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_listing_availability_listing_body_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='body_types/', verbose_name='Силуэт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generations/', verbose_name='Фото'),
        ),
    ]
