# Generated by Django 5.1.15 on 2026-06-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_seed_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('lines', models.JSONField(blank=True, default=list, verbose_name='Строки описания')),
                ('schedule', models.CharField(blank=True, max_length=120, verbose_name='График работы')),
                ('color', models.CharField(default='#F4A6A0', max_length=9, verbose_name='Цвет карточки (hex)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Магазин запчастей',
                'verbose_name_plural': 'Магазины запчастей',
                'ordering': ['order', 'id'],
            },
        ),
    ]
