# Generated by Django 5.1.15 on 2026-06-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_seed_parts_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='vehicle_type',
            field=models.CharField(choices=[('auto', 'Легковая'), ('special', 'Спецтехника'), ('moto', 'Мото')], default='auto', max_length=10, verbose_name='Тип техники'),
        ),
    ]
